'use client'

import { useState } from 'react'
import { Download, FileText, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/Button'

interface StudyGuideDownloaderProps {
  content: string
  topic?: string
  className?: string
}

export function StudyGuideDownloader({ content, topic = "Study Guide", className }: StudyGuideDownloaderProps) {
  const [isDownloading, setIsDownloading] = useState(false)

  const downloadAsPDF = async () => {
    setIsDownloading(true)
    try {
      // Create a formatted HTML version for better PDF rendering
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>${topic} - Study Guide</title>
          <style>
            body { 
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              line-height: 1.6;
              max-width: 800px;
              margin: 0 auto;
              padding: 40px 20px;
              color: #333;
            }
            h1 { 
              color: #2563eb; 
              border-bottom: 3px solid #2563eb;
              padding-bottom: 10px;
              margin-bottom: 30px;
            }
            h2 { 
              color: #1e40af; 
              margin-top: 30px;
              border-left: 4px solid #2563eb;
              padding-left: 15px;
            }
            h3 { 
              color: #3730a3; 
              margin-top: 25px;
            }
            ul, ol { 
              margin: 15px 0;
              padding-left: 25px;
            }
            li { 
              margin: 8px 0;
            }
            strong { 
              color: #1e40af;
              font-weight: 600;
            }
            .quick-reference {
              background: #f0f9ff;
              border: 2px solid #0ea5e9;
              border-radius: 8px;
              padding: 20px;
              margin-top: 30px;
            }
            .example {
              background: #fef3c7;
              border-left: 4px solid #f59e0b;
              padding: 15px;
              margin: 15px 0;
            }
            .practice-problem {
              background: #f0fdf4;
              border-left: 4px solid #22c55e;
              padding: 15px;
              margin: 15px 0;
            }
            @media print {
              body { padding: 20px; }
              h1 { page-break-after: avoid; }
              h2, h3 { page-break-after: avoid; }
            }
          </style>
        </head>
        <body>
          <h1>${topic} - Study Guide</h1>
          ${content.replace(/\n/g, '<br>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}
          <div class="quick-reference">
            <h3>📚 Quick Reference</h3>
            <p><em>Generated by brAIny AI Tutor - Your Personal Learning Assistant</em></p>
          </div>
        </body>
        </html>
      `

      // Create a blob and download
      const blob = new Blob([htmlContent], { type: 'text/html' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${topic.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_study_guide.html`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (error) {
      console.error('Error downloading study guide:', error)
    } finally {
      setIsDownloading(false)
    }
  }

  const downloadAsText = () => {
    setIsDownloading(true)
    try {
      const blob = new Blob([content], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${topic.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_study_guide.txt`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (error) {
      console.error('Error downloading study guide:', error)
    } finally {
      setIsDownloading(false)
    }
  }

  return (
    <div className={`flex gap-2 ${className}`}>
      <Button
        onClick={downloadAsPDF}
        disabled={isDownloading}
        variant="outline"
        size="sm"
        className="flex items-center gap-2 bg-white dark:bg-gray-800 border-gray-300 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700"
      >
        {isDownloading ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : (
          <Download className="w-4 h-4" />
        )}
        <span className="text-sm">Download</span>
      </Button>
      <Button
        onClick={downloadAsText}
        disabled={isDownloading}
        variant="ghost"
        size="sm"
        className="flex items-center gap-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 hover:bg-gray-100 dark:hover:bg-gray-800"
      >
        <FileText className="w-4 h-4" />
        <span className="text-sm">Text</span>
      </Button>
    </div>
  )
}
